id = "python-autodoc"
name = "Python Auto-Doc"
version = "0.0.1"
schema_version = 1
authors = ["Evan Allender <evan.allender@gmail.com>"]
description = "Auto-generates PEP 257 docstrings for Python"
repository = "https://github.com/eallender/zed-python-autodoc"

[language_servers.python-autodoc]
name = "Python Autodoc LSP"
languages = ["python"]
